// File generated by FlutterFire CLI.
// This file is used for demo purposes only
// Replace with actual Firebase configuration from Firebase Console

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYT505sMOsnH7YPVBxilGtffXFakKdGj4',
    appId: '1:14924879038:web:d75bec5e7836bd5e6ffaef',
    messagingSenderId: '14924879038',
    projectId: 'meet2discuss',
    authDomain: 'meet2discuss.firebaseapp.com',
    databaseURL: 'https://meet2discuss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'meet2discuss.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYT505sMOsnH7YPVBxilGtffXFakKdGj4',
    appId: '1:14924879038:android:abcdef123456',
    messagingSenderId: '14924879038',
    projectId: 'meet2discuss',
    databaseURL: 'https://meet2discuss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'meet2discuss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-DEMO-DEMO-DEMO-DEMO-DEMO',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'meet2discuss-demo',
    storageBucket: 'meet2discuss-demo.appspot.com',
    iosBundleId: 'com.example.meet2discuss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-DEMO-DEMO-DEMO-DEMO-DEMO',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'meet2discuss-demo',
    storageBucket: 'meet2discuss-demo.appspot.com',
    iosBundleId: 'com.example.meet2discuss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-DEMO-DEMO-DEMO-DEMO-DEMO',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'meet2discuss-demo',
    storageBucket: 'meet2discuss-demo.appspot.com',
  );
}
